### PR TITLE
Add Exvo exchange rates for BTC, USD and JPY

### PR DESCRIPTION
**Pull request by Ming-Tang**
The existing exchange rates in Electrum-Koto are for Bitcoin, and I have removed them and replaced with Exvo exchange rates.

The USD and JPY rates are based on Exvo rates and the Bitcoin Average API

## Before:
screen shot 2018-05-21 at 13 04 32

## After:

screen shot 2018-05-21 at 13 07 21
screen shot 2018-05-21 at 13 06 50

### CODE REVIEW

**Comment by dragonhuntr** [comment]
Promotes trading in Exvo.io, which turns out to be an exit scam. I say we change it to Bisq exchange rates.

**Comment by Ming-Tang** [comment]
I would agree with this and wait for Bisq (and other exchanges) API to show Koto prices.
I will keep this code just to show how to add a new exchange rate to Electrum-Koto.

**Comment by wo01** [comment]
Exvo maybe scam.
I would like to wait to merge the code

**Comment by Ming-Tang** [comment]
Removed Exvo and added Bisq exchange rate, which does not work currently.
Also added 1 KOTO = 100 sat fixed exchange rate as temporary measure.

**Pull request merged**
